apiVersion: 1
groups:
    - orgId: 1
      name: rps on student app
      folder: limits
      interval: 30s
      rules:
        - uid: det2va9tu85j4a
          title: Too many rps
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: sum(rate(http_requests_total[1m]))
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 100
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          annotations:
            description: Please pay attention to this notification and review other metrics yourself
            summary: Summary RPS on student app more than 100
          labels: {}
          isPaused: false
          notification_settings:
            receiver: senderBot

