apiVersion: 1
groups:
    - orgId: 1
      name: 'Latency p99 '
      folder: limits
      interval: 10s
      rules:
        - uid: det2ws8czyu4gf
          title: Timeout exceeded
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{handler="/students/"}[1m])))
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.5
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: Error
          annotations:
            description: The 99th percentile has exceeded the waiting time, it is recommended to review other metrics yourself.
            summary: Latency more 0.5s
          labels: {}
          isPaused: false
          notification_settings:
            receiver: senderBot

