apiVersion: 1
contactPoints:
    - orgId: 1
      name: senderBot
      receivers:
        - uid: eet2uempeiry8a
          type: telegram
          settings:
            bottoken: 8388740900:AAEJOKgQKkU7R8DQ4gTqruVveinfoDfTHBU
            chatid: "-1002639674497"
            disable_notification: false
            disable_web_page_preview: false
            protect_content: false
          disableResolveMessage: false

