
services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: db
    environment:
      POSTGRES_DB: student_db
      POSTGRES_PASSWORD: pass
    ports:
     - 5432:5432

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    restart: always
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:pass@db:5432/student_db?sslmode=disable"
    depends_on:
      - db

  web:
    build:
      context: ./backend
    container_name: student_app
    ports:
      - 8000:8000
    env_file:
      - ./backend/app/.env
    depends_on:
      - db

  locust:
    build:
      context: ./locust
    ports:
      - 8089:8089
    depends_on:
      - web

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - web
      - postgres_exporter
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/datasources/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/alerting:/etc/grafana/provisioning/alerting/
