global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'student_app'
    static_configs:
      - targets: ['student_app:8000']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

