{
 "title": "Backend",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request duration 50 p",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{handler=\"/students/\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration 99 p",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{handler=\"/students/\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/students/\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}